//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_project_auto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoDBEntities : DbContext
    {
        public AutoDBEntities()
            : base("name=AutoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR> CARS { get; set; }
        public virtual DbSet<COMPREHENSIVE_COVER> COMPREHENSIVE_COVER { get; set; }
        public virtual DbSet<INFO_COMPREHENSIVE_COVER> INFO_COMPREHENSIVE_COVER { get; set; }
        public virtual DbSet<INSURANCE> INSURANCEs { get; set; }
        public virtual DbSet<INSURANCE_INFO> INSURANCE_INFO { get; set; }
        public virtual DbSet<OWNER> OWNERS { get; set; }
    }
}
