//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_project_auto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPREHENSIVE_COVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPREHENSIVE_COVER()
        {
            this.INFO_COMPREHENSIVE_COVER = new HashSet<INFO_COMPREHENSIVE_COVER>();
        }
    
        public int ID { get; set; }
        public Nullable<double> PRICE_CAR { get; set; }
        public string DATE_EXPIRE { get; set; }
        public Nullable<double> FINAL_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFO_COMPREHENSIVE_COVER> INFO_COMPREHENSIVE_COVER { get; set; }
    }
}
