//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_project_auto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFO_COMPREHENSIVE_COVER
    {
        public int ID { get; set; }
        public Nullable<int> CAR_ID { get; set; }
        public Nullable<int> COMPREHENSIVE_COVER_ID { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual COMPREHENSIVE_COVER COMPREHENSIVE_COVER { get; set; }
    }
}
