//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS_project_auto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSURANCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSURANCE()
        {
            this.INSURANCE_INFO = new HashSet<INSURANCE_INFO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ENGINE_LITERS { get; set; }
        public Nullable<int> YEAROFCAR { get; set; }
        public Nullable<int> OWNERAGE { get; set; }
        public Nullable<int> PERIOD { get; set; }
        public string DATE_EXPIRE { get; set; }
        public Nullable<double> PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSURANCE_INFO> INSURANCE_INFO { get; set; }
    }
}
